### ISSUE TITLE
Reporte Escrito

### ISSUE THREAD

**Issue by jlrzarcor** [Rodriguit/Proyecto-final-equipo5-opt-2020#1]
* Reporte se construirá en Overleaf.

- [x] Introducción

- [x] Desarrollo

- [x] Conclusiones

- [x] Fecha entrega avance al 90-95%: *05/12/2020**.

- [x] Deadline finalizar: **08/12/2020**.

**Comment by Rodriguit** [comment]
Se cumple con el apartado de Introducción en: https://es.overleaf.com/project/5fc535eb8fa71982ee3a3c48

**Comment by jlrzarcor** [comment]
**Sprint Review:**

* Feedback realizado por Prof. Erick:

- [x] Typos
- [x] Integrar ErrRelativo en #6 @Lobolc @Rodriguit 
- [x] Bibliografía dentro del reporte

Teminado.

**Comment by jlrzarcor** [comment]
@Rodriguit . De acuerdo, adelante con el cierre del Issue.

**Comment by Rodriguit** [comment]
Listo! De acuerdo. Con base en lo anterior, se cierra el issue.
