### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by jlrzarcor** [Rodriguit/Proyecto-final-equipo5-opt-2020#2]
* Se realizará con Reveals.js

- [ ] Deadline terminar: 08/12/2020

**Comment by Rodriguit** [comment]
Hola! Se comparte liga de presentación: [reveal.js](file:///Users/rodrigo/Documents/MCD/Herramientas/reveal.js-master/index.html)

**Comment by jlrzarcor** [comment]
@Rodriguit , acabo de revisar la liga y no abre. Me la puedes compartir por mensaje, para cargarla en los avances.

**Comment by Rodriguit** [comment]
Con base en lo anterior se cierra este issue!
