### ISSUE TITLE
Cómputo en la Nube

### ISSUE THREAD

**Issue by jlrzarcor** [Rodriguit/Proyecto-final-equipo5-opt-2020#3]
* Construir la infraestructura que nos permita desarrollar la programación de forma homologada para el cómputo en la nube.

- [x] Levantar instancia EC2 en AWS
- [x] Dockerfile (Python)
- [x] Registrar IP's para abrir puertos al equipo y a Erick.
- [x] Bastión

**Comment by Rodriguit** [comment]
Se registran las IP's y se comparte archivo de IPv4-DNS en aaebec3

**Comment by jlrzarcor** [comment]
@Rodriguit Realicé una revisión previa al cierre, envío mis comentarios:

- [x] Integrar un README.md en la carpeta de infraestructura con las imágenes correspondientes de la instancia.
- [x]  Mover los archivos flotantes de main a su carpeta de infraestructura.
- [x] Integrar la carpeta images en infraestructura

**Comment by Rodriguit** [comment]
Se atienden comentarios para cerrar este issue. Saludos!

**Comment by jlrzarcor** [comment]
@Rodriguit De acuerdo con los cambios Rodrigo, adelante con el cierre del Issue.

**Comment by Rodriguit** [comment]
Con base a lo anterior se cierra el issue.
