### ISSUE TITLE
Programación de la Solución

### ISSUE THREAD

**Issue by jlrzarcor** [Rodriguit/Proyecto-final-equipo5-opt-2020#5]
* Implementar la solución en Python al problema de estimación por Máxima Verosimilitud.

- [x] Funciones
- [x] Integración desarrollo
- [x] Aproximación: métodos de descenso
- [x] Optimización

**Comment by Rodriguit** [comment]
Hola @Lobolc  te propongo hacer una generalización de la función!

**Comment by Rodriguit** [comment]
Saludos! Hola @Lobolc y @jlrzarcor  ... podrían agregar por favor la función que grafique el gradiente?

**Comment by jlrzarcor** [comment]
Scrum Review: 06/12/2020 (previo a la entrega del avance a Erick).

* Durante sesión de trabajo conjunto, se terminó el desarrollo el desarrollo de programación para la integración de la solución de nuestro problema de optimización y se realizaron pruebas de consistencia.

@Lobolc , @jreyesgar93 dado que las actividades de este Issue se han terminado exitosamente, les pido ya cerrarlo y enviar a revisión.

**Comment by Rodriguit** [comment]
Con base a lo anterior, se cierra issue5
