### ISSUE TITLE
Implementación a Distribuciones Conocidas

### ISSUE THREAD

**Issue by jlrzarcor** [Rodriguit/Proyecto-final-equipo5-opt-2020#6]
* Maximizar los parámetros de las siguientes distribuciones implementando los algoritmos realizados.

- [x] Distribución Poisson
- [x] Distribución Normal

**Comment by Rodriguit** [comment]
Hola. @jlrzarcor  ... Resolvimos la estimación de parámetros para la distribución Poisson. El método de optimización será por Newton-Raphson.

**Comment by jlrzarcor** [comment]
**Equipo de Programación** @Lobolc @Rodriguit @jreyesgar93 , necesitamos que se integre en un sólo archivo todas las funciones que hemos creado para que se tenga un sólo archivo __init__.py o un archivo utils, la idea es no tener demasiados archivo de programación y que los reportes contengan únicamente las llamadas a las funciones, los resultados y los gráficos de las soluciones que estamos planteando a nuestro problema de optimización.

@

**Comment by jreyesgar93** [comment]
@Rodriguit @Lobolc profa incluyan sus funciones en la carpeta MLE. Ademas incorporar su notebook al de Maxima Verosimilitud para tener uno solo. Borrar los archivos que ya no sean necesarios
@jlrzarcor Hay unas carpetas que ya no se usan. Notebooks y data por ejemplo. Se vuelve un problema tener las cosas ahí a la hora de definir los paths. Favor de borrar las que estén vacías.

**Comment by jlrzarcor** [comment]
@Rodriguit , @Lobolc actividades a completar:

* Integrar la Carpeta MLE en Código para que al enviarlo al repo final esté integrado.
* Verificar si es posible borrar la carpeta Otros (appliedrussian.ipynb y newton_raphson.ipynb).
* Verificar si es posible y en su caso integrar, las clases y funciones en Maxima_verosimilitud.ipynb (código) a __init__.py.

**Comment by Rodriguit** [comment]
Listo @jlrzarcor  ... se realizaron las modificaciones solicitadas para dejar la carpeta código lo más limpia posible.
Saludos!

**Comment by jlrzarcor** [comment]
**Scrum Closing Issue Session:**

@Rodriguit , @Lobolc , se revisan los cambios y ajustes que llevaron a cabo; modificamos el pytest por la reubicación de la carpeta MLE a código dado que al validarlo nos arrojó error; cambios validados para el error relativo de acuerdo a Feedbak de Erick (integrado en #1). 

Con base en lo anterior, adelante con el cierre.

**Comment by Rodriguit** [comment]
Se cierra issue con base a lo anterior
